
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;
	private global::Gtk.Entry txtUsuario;
	private global::Gtk.Entry txtPass;
	private global::Gtk.Button button3;
	private global::Gtk.Label label1;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Login");
		this.Icon = global::Stetic.IconLoader.LoadIcon (this, "stock_weather-night-clear", global::Gtk.IconSize.Menu);
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.Resizable = false;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed ();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.txtUsuario = new global::Gtk.Entry ();
		this.txtUsuario.TooltipMarkup = "Ingrese nombre de usuario";
		this.txtUsuario.CanFocus = true;
		this.txtUsuario.Name = "txtUsuario";
		this.txtUsuario.Text = global::Mono.Unix.Catalog.GetString ("Usuario");
		this.txtUsuario.IsEditable = true;
		this.txtUsuario.InvisibleChar = '●';
		this.txtUsuario.Xalign = 0.5F;
		this.fixed1.Add (this.txtUsuario);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.txtUsuario]));
		w1.X = 111;
		w1.Y = 47;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.txtPass = new global::Gtk.Entry ();
		this.txtPass.TooltipMarkup = "Ingrese password";
		this.txtPass.CanFocus = true;
		this.txtPass.Name = "txtPass";
		this.txtPass.Text = global::Mono.Unix.Catalog.GetString ("Password");
		this.txtPass.IsEditable = true;
		this.txtPass.Visibility = false;
		this.txtPass.InvisibleChar = '●';
		this.txtPass.Xalign = 0.5F;
		this.fixed1.Add (this.txtPass);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.txtPass]));
		w2.X = 112;
		w2.Y = 115;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button3 = new global::Gtk.Button ();
		this.button3.CanFocus = true;
		this.button3.Name = "button3";
		this.button3.UseUnderline = true;
		this.button3.Label = global::Mono.Unix.Catalog.GetString ("Aceptar");
		this.fixed1.Add (this.button3);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.button3]));
		w3.X = 166;
		w3.Y = 169;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("HOLA");
		this.fixed1.Add (this.label1);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label1]));
		w4.X = 168;
		w4.Y = 85;
		this.Add (this.fixed1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 261;
		this.label1.Hide ();
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.button3.Clicked += new global::System.EventHandler (this.botonApachurrado);
	}
}
